### ISSUE TITLE
Comparison to Mimetis/JsonExtensions

### ISSUE THREAD

**Issue by symbiogenesis** [bjornharrtell/Utf8JsonStreamReader#10]
Just alerting you to another library with a similar goal. Would be worthwhile to produce comparison benchmarks, or collaborate in some way. To know the relative merits.

https://github.com/Mimetis/JsonExtensions

There are also some others:

https://github.com/gragra33/Utf8JsonAsyncStreamReader

https://github.com/Macross-Software/core/blob/develop/ClassLibraries/Macross.Json.Extensions/Code/System.Text.Json/Utf8JsonStreamReader.cs

**Comment by bjornharrtell** [comment]
@symbiogenesis doesn't look too good for the competition. https://github.com/Mimetis/JsonExtensions doesn't seem to publish to nuget, https://github.com/gragra33/Utf8JsonAsyncStreamReader is about 4x slower (I added it locally to my benchmark and compared) and it's not clear to me how to use Macross.Json.Extensions and it seems a bit out of date and/or unmaintained.
