### ISSUE TITLE
Forslag

### ISSUE THREAD

**Issue by EskeRahn** [bjornharrtell/Utf8JsonStreamReader#2]
Det er jo dig der har fat i stream, og du sender en buffer videre til uft8reader.  
Kunne du ændre create fra default, specifik size til også at have en Auto med et angivet maximum  
Tænker et hvis du får fejl fra UR, da at udvide din lokale buffer, fylde den op fra stream, og så prøve igen.  
Den kunne jo være noget med at starte med fx de 8K, og så lægge 10% mere oveni.

...det kunne være din nuværende der var den initielle og så en ny optional med max, der havde fall back til initiel for ingen auto....

**Comment by bjornharrtell** [comment]
Out of scope. :D
