### ISSUE TITLE
Suggestion: do not re-allocate a queue on each loop iteration

### ISSUE THREAD

**Issue by bent-rasmussen** [bjornharrtell/Utf8JsonStreamReader#7]
https://github.com/bjornharrtell/Utf8JsonStreamReader/blob/5e9a5680209f136d2bea5d4f2d5b1d99b7a1cae3/Utf8JsonStreamReader/Utf8JsonStreamReader.cs#L81

Have you considered just allocating a List before processing, e.g.:

```csharp
    public async IAsyncEnumerable<JsonResult> ToAsyncEnumerable(Stream stream)
    {
        var results = new List<JsonResult>(); // pre-allocate results
        while (!done)
        {
            var remaining = bufferLength - offset;
            if (remaining > 0)
                buffer[offset..].CopyTo(buffer);
            var readLength = await stream.ReadAtLeastAsync(buffer[remaining..], bufferSize - remaining, false);
            bufferLength = readLength + remaining;
            offset = 0;
            done = bufferLength < bufferSize;
            // do not allocate this on each loop iteration: var results = new Queue<JsonResult>();
            ReadBuffer((ref Utf8JsonReader reader) => results.Add(new JsonResult(reader.TokenType, Utf8JsonHelpers.GetValue(ref reader))));
            foreach (var item in results)
                yield return item;
            results.Clear(); // clear results again to avoid growing list to entire result set
        }
    }
```

It seems to improve benchmarks and would positively impact memory usage, although the benchmarks are not currently configured to show use the MemoryDiagnoser (https://adamsitnik.com/the-new-Memory-Diagnoser/).

**Comment by bjornharrtell** [comment]
Good catch, I agree and will make change. But I wonder, why would List be better than Queue? I've tried both and it doesn't seem to affect performance.

**Comment by bent-rasmussen** [comment]
Oh I'm not so sure `List<T>` makes a big difference compared to moving the collection outside the while loop but I figured it would be at least as good as `Queue<T>`, and its `Clear` method is probably fast as well, whereas I don't know with `Queue<T>`.
